package dessine_module;


/**
* dessine_module/ByteArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 22 h 03 CET
*/

public final class ByteArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public ByteArrayHolder ()
  {
  }

  public ByteArrayHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dessine_module.ByteArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dessine_module.ByteArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dessine_module.ByteArrayHelper.type ();
  }

}
