package dessine_module;


/**
* dessine_module/CommunicationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 22 h 03 CET
*/

abstract public class CommunicationHelper
{
  private static String  _id = "IDL:dessine_module/Communication:1.0";

  public static void insert (org.omg.CORBA.Any a, dessine_module.Communication that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dessine_module.Communication extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dessine_module.CommunicationHelper.id (), "Communication");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dessine_module.Communication read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CommunicationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dessine_module.Communication value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dessine_module.Communication narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dessine_module.Communication)
      return (dessine_module.Communication)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dessine_module._CommunicationStub stub = new dessine_module._CommunicationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dessine_module.Communication unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dessine_module.Communication)
      return (dessine_module.Communication)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dessine_module._CommunicationStub stub = new dessine_module._CommunicationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
