package dessine_module;


/**
* dessine_module/CommunicationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public abstract class CommunicationPOA extends org.omg.PortableServer.Servant
 implements dessine_module.CommunicationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerProducer", new java.lang.Integer (0));
    _methods.put ("pushInfo", new java.lang.Integer (1));
    _methods.put ("readyForPull", new java.lang.Integer (2));
    _methods.put ("pullComments", new java.lang.Integer (3));
    _methods.put ("disconnect", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dessine_module/Communication/registerProducer
       {
         try {
           dessine_module.HostInfo info = dessine_module.HostInfoHelper.read (in);
           this.registerProducer (info);
           out = $rh.createReply();
         } catch (dessine_module.Reject $ex) {
           out = $rh.createExceptionReply ();
           dessine_module.RejectHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // dessine_module/Communication/pushInfo
       {
         try {
           dessine_module.Image image = dessine_module.ImageHelper.read (in);
           dessine_module.HostInfo producerInfo = dessine_module.HostInfoHelper.read (in);
           String $result = null;
           $result = this.pushInfo (image, producerInfo);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (dessine_module.Reject $ex) {
           out = $rh.createExceptionReply ();
           dessine_module.RejectHelper.write (out, $ex);
         }
         break;
       }


  //Return a ticket that will be used for pulling the response
       case 2:  // dessine_module/Communication/readyForPull
       {
         String ticket = in.read_string ();
         this.readyForPull (ticket);
         out = $rh.createReply();
         break;
       }

       case 3:  // dessine_module/Communication/pullComments
       {
         try {
           String ticket = in.read_string ();
           String $result[] = null;
           $result = this.pullComments (ticket);
           out = $rh.createReply();
           dessine_module.StringArrayHelper.write (out, $result);
         } catch (dessine_module.Reject $ex) {
           out = $rh.createExceptionReply ();
           dessine_module.RejectHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // dessine_module/Communication/disconnect
       {
         dessine_module.HostInfo info = dessine_module.HostInfoHelper.read (in);
         this.disconnect (info);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dessine_module/Communication:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Communication _this() 
  {
    return CommunicationHelper.narrow(
    super._this_object());
  }

  public Communication _this(org.omg.CORBA.ORB orb) 
  {
    return CommunicationHelper.narrow(
    super._this_object(orb));
  }


} // class CommunicationPOA
