package dessine_module;


/**
* dessine_module/DessineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public interface DessineOperations 
{
  boolean sendImage (dessine_module.Image img, dessine_module.HostInfo destination) throws dessine_module.Reject;
  boolean sendComments (String[] comments, dessine_module.HostInfo destination) throws dessine_module.Reject;
  boolean sendImageWithComments (dessine_module.Image img, String[] comments, dessine_module.HostInfo destination) throws dessine_module.Reject;
} // interface DessineOperations
