package dessine_module;


/**
* dessine_module/DessinePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public abstract class DessinePOA extends org.omg.PortableServer.Servant
 implements dessine_module.DessineOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendImage", new java.lang.Integer (0));
    _methods.put ("sendComments", new java.lang.Integer (1));
    _methods.put ("sendImageWithComments", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dessine_module/Dessine/sendImage
       {
         try {
           dessine_module.Image img = dessine_module.ImageHelper.read (in);
           dessine_module.HostInfo destination = dessine_module.HostInfoHelper.read (in);
           boolean $result = false;
           $result = this.sendImage (img, destination);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (dessine_module.Reject $ex) {
           out = $rh.createExceptionReply ();
           dessine_module.RejectHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // dessine_module/Dessine/sendComments
       {
         try {
           String comments[] = dessine_module.StringArrayHelper.read (in);
           dessine_module.HostInfo destination = dessine_module.HostInfoHelper.read (in);
           boolean $result = false;
           $result = this.sendComments (comments, destination);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (dessine_module.Reject $ex) {
           out = $rh.createExceptionReply ();
           dessine_module.RejectHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // dessine_module/Dessine/sendImageWithComments
       {
         try {
           dessine_module.Image img = dessine_module.ImageHelper.read (in);
           String comments[] = dessine_module.StringArrayHelper.read (in);
           dessine_module.HostInfo destination = dessine_module.HostInfoHelper.read (in);
           boolean $result = false;
           $result = this.sendImageWithComments (img, comments, destination);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (dessine_module.Reject $ex) {
           out = $rh.createExceptionReply ();
           dessine_module.RejectHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dessine_module/Dessine:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dessine _this() 
  {
    return DessineHelper.narrow(
    super._this_object());
  }

  public Dessine _this(org.omg.CORBA.ORB orb) 
  {
    return DessineHelper.narrow(
    super._this_object(orb));
  }


} // class DessinePOA
