package dessine_module;


/**
* dessine_module/HostInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public final class HostInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String ipAddress = null;
  public String port = null;
  public String hostName = null;
  public String ior = null;
  public dessine_module.HostType type = null;

  public HostInfo ()
  {
  } // ctor

  public HostInfo (String _ipAddress, String _port, String _hostName, String _ior, dessine_module.HostType _type)
  {
    ipAddress = _ipAddress;
    port = _port;
    hostName = _hostName;
    ior = _ior;
    type = _type;
  } // ctor

} // class HostInfo
