package dessine_module;


/**
* dessine_module/HostTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 22 h 03 CET
*/

abstract public class HostTypeHelper
{
  private static String  _id = "IDL:dessine_module/HostType:1.0";

  public static void insert (org.omg.CORBA.Any a, dessine_module.HostType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dessine_module.HostType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (dessine_module.HostTypeHelper.id (), "HostType", new String[] { "CLIENT", "SERVER"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dessine_module.HostType read (org.omg.CORBA.portable.InputStream istream)
  {
    return dessine_module.HostType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dessine_module.HostType value)
  {
    ostream.write_long (value.value ());
  }

}
