package dessine_module;


/**
* dessine_module/HostInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

abstract public class HostInfoHelper
{
  private static String  _id = "IDL:dessine_module/HostInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, dessine_module.HostInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dessine_module.HostInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "ipAddress",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "port",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "hostName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "ior",
            _tcOf_members0,
            null);
          _tcOf_members0 = dessine_module.HostTypeHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (dessine_module.HostInfoHelper.id (), "HostInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dessine_module.HostInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    dessine_module.HostInfo value = new dessine_module.HostInfo ();
    value.ipAddress = istream.read_string ();
    value.port = istream.read_string ();
    value.hostName = istream.read_string ();
    value.ior = istream.read_string ();
    value.type = dessine_module.HostTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dessine_module.HostInfo value)
  {
    ostream.write_string (value.ipAddress);
    ostream.write_string (value.port);
    ostream.write_string (value.hostName);
    ostream.write_string (value.ior);
    dessine_module.HostTypeHelper.write (ostream, value.type);
  }

}
