package dessine_module;

/**
* dessine_module/ImageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public final class ImageHolder implements org.omg.CORBA.portable.Streamable
{
  public dessine_module.Image value = null;

  public ImageHolder ()
  {
  }

  public ImageHolder (dessine_module.Image initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dessine_module.ImageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dessine_module.ImageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dessine_module.ImageHelper.type ();
  }

}
