package dessine_module;


/**
* dessine_module/Image.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public final class Image implements org.omg.CORBA.portable.IDLEntity
{
  public byte data[] = null;
  public int bytesCount = (int)0;
  public int height = (int)0;
  public int width = (int)0;

  public Image ()
  {
  } // ctor

  public Image (byte[] _data, int _bytesCount, int _height, int _width)
  {
    data = _data;
    bytesCount = _bytesCount;
    height = _height;
    width = _width;
  } // ctor

} // class Image
