package dessine_module;


/**
* dessine_module/Reject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mercredi 25 janvier 2017 21 h 40 CET
*/

public final class Reject extends org.omg.CORBA.UserException
{
  public String message = null;

  public Reject ()
  {
    super(RejectHelper.id());
  } // ctor

  public Reject (String _message)
  {
    super(RejectHelper.id());
    message = _message;
  } // ctor


  public Reject (String $reason, String _message)
  {
    super(RejectHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class Reject
